apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: pv1
  accessModes:
    - ReadWriteMany
  nfs:
    path: /pv1
    server: 172.16.3.24
