---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pv2
  selector:
    matchLabels:
      pv-id: pv2
  resources:
    requests:
      storage: 5Gi
